name: Evening Workflow
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 14 * * *"

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 2-Rq-2/Railway-Games  # 替换为您的仓库地址

      - name: Configure Git
        run: |
          git config --global user.name "2-Rq-2"
          git config --global user.email "loslao11@mailbox.org"
          git config --global credential.helper store

      - name: Check File Existence
        run: |
          current_hour=$(TZ='Asia/Singapore' date +"%H")
          if [[ $current_hour -ge 6 && $current_hour -lt 21 ]]; then
            if [[ -f "app.js" ]]; then
              cp app.js app2.js  # 复制 app.js 内容到 app2.js
              echo "Switched to app2.js"
              rm -f app.js  # 删除 app.js 文件
              echo "Deleted app.js"
              git add app2.js
              git commit -m "Switched to app2.js" || true
              git push origin HEAD
            else
              echo "app.js not found, skipping file switch"
            fi
          else
            echo "Skipping file switch"
          fi

