name: Morning Workflow
on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 2-Rq-2/Railway-Games

      - name: Configure Git
        run: |
          git config --global user.name "2-Rq-2"
          git config --global user.email "loslao11@mailbox.org"
          git config --global credential.helper store

      - name: Check File Existence
        run: |
          current_hour=$(TZ='Asia/Singapore' date +"%H")
          if [[ $current_hour -ge 6 && $current_hour -lt 21 ]]; then
            if [[ -f "app2.js" ]]; then
              mv app2.js app.js
              echo "Switched to app.js"
            else
              echo "app2.js not found, skipping file switch"
            fi
          else
            echo "Skipping file switch"
          fi

      - name: Commit Changes
        run: |
          git add app.js
          git commit -m "Switched to app.js" || true
          git push origin HEAD
