name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Set Railway API Token
        run: railway login --api-token ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway
        run: railway up --project-name dark-houses --service-name dark-houses
