name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Railway CLI
        uses: railwayapp/cli-action@v1

      - name: Set Railway API Token
        run: echo "RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy to Railway
        run: railway up --project-name MyCustomProject --service-name MyCustomService
