name: File Switch Workflow
on:
  push:
    branches: [main]
  schedule:
    - cron: "5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "2-Rq-2"
          git config --global user.email "loslao11@mailbox.org"
          git config --global credential.helper store

      - name: Check if app.js exists
        run: |
          if [[ -f "app.js" ]]; then
            echo "app.js file exists"
            mv app.js app2.js
            echo "Switched to app2.js"
          else
            echo "app.js not found, skipping file switch"
          fi

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "File switch" || true
          git push origin HEAD
