name: File Switch Workflow

on:
  push:
    branches: [main]
  schedule:
    - cron: "6,10 * * * *"

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: 2-Rq-2/Railway-Games

      - name: Configure Git
        run: |
          git config --global user.name "2-Rq-2"
          git config --global user.email "loslao11@mailbox.org"
          git config --global credential.helper store

      - name: Check File Existence
        run: |
          current_hour=$(TZ='Asia/Singapore' date +"%H")
          if [[ $current_hour -ge 6 && $current_hour -lt 21 ]]; then
            if [[ -f "app2.js" ]]; then
              if [[ -f "app.js" ]]; then
                rm -f app.js
                echo "Deleted app.js"
              fi
              mv app2.js app.js
              echo "Switched to app.js"
            else
              echo "app2.js not found, skipping file switch"
            fi
          else
            if [[ -f "app.js" ]]; then
              if [[ -f "app2.js" ]]; then
                rm -f app2.js
                echo "Deleted app2.js"
              fi
            fi
            echo "Skipping file switch"
          fi

      - name: Commit Changes
        run: |
          git add app.js app2.js
          git commit -m "File switch" || true
          git push origin HEAD

