name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Curl
        run: sudo apt-get install curl -y

      - name: Set Railway API Token
        run: echo "RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy to Railway
        run: |
          curl --request POST \
            --url "https://backboard.railway.app/graphql/v2/services/d29a167c-0013-49eb-956b-3005b4205890/deploy" \
            --header 'Content-Type: application/json' \
            --header "Authorization: Bearer $RAILWAY_API_TOKEN" \
            --data '{}'
