name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl -y

      - name: Set Railway API Token
        run: echo "RAILWAY_API_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV

      - name: Download GitHub repository code
        run: |
          curl -LOk "https://github.com/2-Rq-2/Railway-Games/archive/main.tar.gz"
          tar -xf main.tar.gz --strip-components=1

      - name: Create Railway service
        run: |
          curl --request POST \
            --url https://backboard.railway.app/graphql/v2 \
            --header "Authorization: Bearer $RAILWAY_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data '{"query":"mutation { createService(name: \"dark-houses\") { id } }"}'

      - name: Upload code to Railway service
        run: |
          curl --request POST \
            --url https://backboard.railway.app/graphql/v2 \
            --header "Authorization: Bearer $RAILWAY_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data '{"query":"mutation { uploadCode(serviceId: \"d29a167c-0013-49eb-956b-3005b4205890\", files: [{path: \".\", sourceType: GITHUB, url: \"https://github.com/2-Rq-2/Railway-Games/archive/main.tar.gz\"}]) { success errors } }"}'
