name: File Switch Workflow
on:
  push:
    branches: [main]
  schedule:
    - cron: "*/6 * * * *"
  schedule:
    - cron: "*/10 * * * *"

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "2-Rq-2"
          git config --global user.email "loslao11@mailbox.org"
          git config --global credential.helper store

      - name: Check File Existence and Switch
        run: |
          current_minute=$(date +"%M")
          if [[ $current_minute -eq 0 || $current_minute -eq 6 ]]; then
            if [[ -f "app2.js" ]]; then
              mv app2.js app.js
              echo "Switched to app.js"
            else
              echo "app2.js not found, skipping file switch"
            fi
          elif [[ $current_minute -eq 10 ]]; then
            if [[ -f "app.js" ]]; then
              mv app.js app2.js
              echo "Switched to app2.js"
            else
              echo "app.js not found, skipping file switch"
            fi
          else
            echo "Skipping file switch"
          fi

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "File switch" || true
          git push origin HEAD
